[package]
name = "example-counter"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.4"
axum-liveview = { path = "../../axum-liveview", version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.0", features = ["full"] }
