[package]
name = "xtask"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
# be _very_ careful about adding dependencies here. Wanna keep xtasks compiling
# quickly
flate2 = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
structopt = "0.3"
