[package]
name = "example-clock"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = "0.6"
axum-live-view = { path = "../../axum-live-view", version = "0.1", features = [
  "precompiled-js",
] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
tower-http = { version = "0.3", features = ["fs"] }
time = { version = "0.3", features = ["local-offset", "formatting"] }
